### PR TITLE
project structure changes

### PR DESCRIPTION
**Pull request by JayusJay**
Added new folders and config files

### CODE REVIEW

**Comment by awal99** [comment]
Great @Jonathan. I have seen the change. Looking through, i would approve if all is well else i would send you another comment.

**Review by awal99 — COMMENTED** [review]
@JayusJay i cannot see the .env file. extract the localstorage key and other constants to the .env file and commit it. (i assume the one you would commit is just the dev version)

**Comment by JayusJay** [comment]
> @JayusJay i cannot see the .env file. extract the localstorage key and other constants to the .env file and commit it. (i assume the one you would commit is just the dev version)

Alright.

**Comment by JayusJay** [comment]
> > @JayusJay i cannot see the .env file. extract the localstorage key and other constants to the .env file and commit it. (i assume the one you would commit is just the dev version)
> 
> Alright.

.env file added and configured.

**Pull request merged**
